[package]
name = "client"
version = "0.1.0"
authors = ["linfeng <linfeng@crypto.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7"
structopt = "0.3"
subtle-encoding = "0.5"
signatory = { path = "../../.."}
signatory-sgx = { path = "../../../signatory-sgx"}
