[package]
name = "sgx_app"
version = "0.1.0"
authors = ["linfeng <linfeng@crypto.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.9"
log = "0.4"
signatory-sgx = { path = "../../../signatory-sgx", default-features = false, features = ["sgx"] }
